apiVersion: v2
name: kyverno-aws-adapter
description: Helm chart for the Kyverno AWS Adapter
type: application
version: 0.1.0
appVersion: 0.1.0
keywords:
  - kubernetes
  - nirmata
  - kyverno
  - aws
  - adapter
  - policy
maintainers:
  - name: Nirmata
    url: https://nirmata.com/
