# Default values for kyverno-aws-adapter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace:
  # create namespace
  create: true
  # name of the namespace to install kyverno aws adapter, defaults to 'nirmata'
  name: nirmata

# REQUIRED To access AWS API
roleArn:

# If not defined, defaults to 30 (seconds)
pollInterval: 15

eksCluster:
  name: eks-test
  region: us-west-1

# REQUIRED To pull the private image
registryConfig:
  username:
  password:

image:
  repository: ghcr.io/nirmata/kyverno-aws-adapter
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: v0.1.0

nameOverride: ""
fullnameOverride: ""
