---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: awsadapterconfigs.security.nirmata.io
spec:
  group: security.nirmata.io
  names:
    kind: AWSAdapterConfig
    listKind: AWSAdapterConfigList
    plural: awsadapterconfigs
    shortNames:
    - awsacfg
    singular: awsadapterconfig
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.name
      name: Cluster Name
      type: string
    - jsonPath: .spec.region
      name: Region
      type: string
    - jsonPath: .status.eksCluster.status
      name: Cluster Status
      type: string
    - jsonPath: .status.eksCluster.kubernetesVersion
      name: Kubernetes Version
      type: string
    - jsonPath: .status.lastPollInfo.status
      name: Last Polled Status
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: AWSAdapterConfig is the Schema for the awsadapterconfigs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AWSAdapterConfigSpec defines the desired state of AWSAdapterConfig
            properties:
              name:
                description: EKS cluster's name
                type: string
              region:
                description: EKS cluster's region
                type: string
            required:
            - name
            - region
            type: object
          status:
            description: AWSAdapterConfigStatus defines the observed state of AWSAdapterConfig
            properties:
              eksCluster:
                description: 'EKS cluster details fetched from AWS For details of
                  individual fields, refer to AWS SDK docs: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/eks@v1.22.1/types#Cluster'
                properties:
                  addons:
                    items:
                      type: string
                    type: array
                  arn:
                    type: string
                  certificate:
                    type: string
                  compute:
                    description: EKSCompute contains node groups and fargate profiles
                      of the EKS cluster
                    properties:
                      fargateProfiles:
                        items:
                          type: string
                        type: array
                      nodeGroups:
                        items:
                          description: EKSNodeGroup contains info of the EKS cluster's
                            node group
                          properties:
                            amiReleaseVersion:
                              type: string
                            amiType:
                              type: string
                            capacityType:
                              type: string
                            createdAt:
                              type: string
                            diskSize:
                              format: int32
                              type: integer
                            healthIssues:
                              items:
                                description: EKSNodeGroupHealthIssue contains info
                                  of any health issue in the EKS cluster's node group
                                properties:
                                  code:
                                    type: string
                                  message:
                                    type: string
                                  resourceIDs:
                                    items:
                                      type: string
                                    type: array
                                type: object
                              type: array
                            instanceTypes:
                              items:
                                type: string
                              type: array
                            labels:
                              additionalProperties:
                                type: string
                              type: object
                            launchTemplate:
                              description: EC2LaunchTemplate contains launch template
                                info the EKS cluster's node group
                              properties:
                                id:
                                  type: string
                                name:
                                  type: string
                                version:
                                  type: string
                              type: object
                            name:
                              type: string
                            nodeGroupArn:
                              type: string
                            nodeRole:
                              type: string
                            remoteAccessConfig:
                              description: EKSNodeGroupRemoteAccessConfig contains
                                remote access configuration of the EKS cluster's node
                                group
                              properties:
                                ec2SSHKey:
                                  type: string
                                sourceSecurityGroups:
                                  items:
                                    type: string
                                  type: array
                              type: object
                            resources:
                              description: EKSNodeGroupResources contains info of
                                ASG and remote access SG for node group
                              properties:
                                autoScalingGroups:
                                  items:
                                    type: string
                                  type: array
                                remoteAccessSecurityGroup:
                                  type: string
                              type: object
                            scalingConfig:
                              description: EKSNodeGroupScalingConfig contains scaling
                                configuration of  the EKS cluster's node group
                              properties:
                                desiredSize:
                                  format: int32
                                  type: integer
                                maxSize:
                                  format: int32
                                  type: integer
                                minSize:
                                  format: int32
                                  type: integer
                              type: object
                            status:
                              type: string
                            subnets:
                              items:
                                type: string
                              type: array
                            tags:
                              additionalProperties:
                                type: string
                              type: object
                            taints:
                              items:
                                description: EKSNodeGroupTaint contains info of taints
                                  in the EKS cluster's node group
                                properties:
                                  effect:
                                    type: string
                                  key:
                                    type: string
                                  value:
                                    type: string
                                type: object
                              type: array
                            updateConfig:
                              description: EKSNodeGroupUpdateConfig contains number/percentage
                                of node groups that can be updated in parallel
                              properties:
                                maxUnavailable:
                                  format: int32
                                  type: integer
                                maxUnavailablePercentage:
                                  format: int32
                                  type: integer
                              type: object
                          type: object
                        type: array
                      reservations:
                        items:
                          properties:
                            instances:
                              items:
                                properties:
                                  httpPutResponseHopLimit:
                                    format: int32
                                    type: integer
                                  publicDnsName:
                                    type: string
                                type: object
                              type: array
                          type: object
                        type: array
                    type: object
                  createdAt:
                    type: string
                  encryptionConfig:
                    items:
                      description: EKSEncryptionConfig contains encryption configuration
                        of the EKS cluster
                      properties:
                        keyARN:
                          type: string
                        resources:
                          items:
                            type: string
                          type: array
                      type: object
                    type: array
                  endpoint:
                    type: string
                  id:
                    type: string
                  identityProviderConfigs:
                    items:
                      type: string
                    type: array
                  kubernetesVersion:
                    type: string
                  logging:
                    description: EKSLogging contains info of which logs are enabled
                    properties:
                      apiServer:
                        type: boolean
                      audit:
                        type: boolean
                      authenticator:
                        type: boolean
                      controllerManager:
                        type: boolean
                      scheduler:
                        type: boolean
                    type: object
                  name:
                    type: string
                  networking:
                    description: EKSNetworking contains networking configuration of
                      the EKS cluster
                    properties:
                      ipFamily:
                        type: string
                      serviceIPv4CIDR:
                        type: string
                      serviceIPv6CIDR:
                        type: string
                      vpc:
                        description: EKSVpcConfig contains VPC configuration of the
                          EKS cluster
                        properties:
                          clusterSecurityGroupID:
                            type: string
                          endpointPrivateAccess:
                            type: boolean
                          endpointPublicAccess:
                            type: boolean
                          flowLogsEnabled:
                            type: boolean
                          publicAccessCIDRs:
                            items:
                              type: string
                            type: array
                          securityGroupIDs:
                            items:
                              type: string
                            type: array
                          subnetIDs:
                            items:
                              type: string
                            type: array
                          vpcID:
                            type: string
                        type: object
                    type: object
                  oidcProvider:
                    type: string
                  platformVersion:
                    type: string
                  region:
                    type: string
                  roleArn:
                    type: string
                  status:
                    type: string
                  tags:
                    additionalProperties:
                      type: string
                    type: object
                required:
                - name
                - region
                - status
                type: object
              lastPollInfo:
                description: Information on when the adapter last tried to fetch the
                  EKS cluster details
                properties:
                  failure:
                    description: PollFailure contains the Error and relevant Message
                      if got Failure in last poll
                    properties:
                      error:
                        type: string
                      message:
                        type: string
                    required:
                    - error
                    - message
                    type: object
                  status:
                    type: string
                  timestamp:
                    format: date-time
                    type: string
                type: object
              lastUpdatedTimestamp:
                description: Timestamp when the Status was last updated
                format: date-time
                type: string
            required:
            - lastPollInfo
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
